model:
  base_learning_rate: 1.0e-06
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    #ckpt_path: Downloaded_checkpoints/ffhq_ldm.ckpt
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: image
    cond_stage_key: aus
    image_size: 64
    channels: 3
    cond_stage_trainable: true
    conditioning_key: crossattn
    monitor: val/loss_simple_ema
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 64
        in_channels: 3
        out_channels: 3
        model_channels: 224
        attention_resolutions:
        #note: this isn\t actually the resolution but
        # the downsampling factor, i.e. this corresnponds to
        # attention on spatial resolution 8,16,32, as the
        # spatial reolution of the latents is 32 for f8
        - 4
        - 2
        - 1
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 3
        - 4
        num_head_channels: 32
        use_spatial_transformer: true
        transformer_depth: 1
        context_dim: 512
    first_stage_config:
      target: ldm.models.autoencoder.VQModelInterface
      params:
        embed_dim: 3
        n_embed: 8192
        ckpt_path: Downloaded_checkpoints/VQ/VQ_AU_Epoch14.ckpt
        ddconfig:
          double_z: false
          z_channels: 3
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions:
          - 
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config:
      target: ldm.modules.encoders.modules.MultiClassEmbedder
      params:
        embed_dim: 512
        n_aus: 18
        key: aus
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 10
    num_workers: 6
    shuffle_val_dataloader: True
    train:
      target: ldm.data.dataset.MultiDatasetTrain
      params:
        datasets: ['BP4D', 'DISFA']
        aus: ['AU1', 'AU2', 'AU4', 'AU6', 'AU7', 'AU9', 'AU10','AU12', 'AU14', 'AU15', 'AU17','AU20', 'AU23', 'AU24', 'AU25','AU26','AU27','AU43']
        size: 256
        mcManager: True
        
    validation:
      target: ldm.data.dataset.MultiDatasetVal
      params:
        datasets: ['BP4D', 'DISFA']
        aus: ['AU1', 'AU2', 'AU4', 'AU6', 'AU7', 'AU9', 'AU10','AU12', 'AU14', 'AU15', 'AU17','AU20', 'AU23', 'AU24', 'AU25','AU26','AU27','AU43']
        size: 256
        mcManager: True
        

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency:
          train: 5000
          val: 1800
        max_images: 4
        increase_log_steps: False
        log_on_batch_idx: True

  trainer:
    max_epochs: 50
    benchmark: True